# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a8e24b623ef53c9a3a2f218eb4ea2f1b4b3ff07564610a360fbabcebe827eebee1d78772fb72aad961bda645d4362ef336eb507ed16907f5d8297a862bae1e9

test:
  secret_key_base: 2bd24b48b755212af13d990be2e141c7491142d34f525df18d63ef1e85edaf11934e28f5153c595514910c89ec0cd73279a28cfad67f2090547d2dd5d9ebc7c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
